# Generated by Django 3.2.8 on 2021-10-27 12:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PowerPlants',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.TextField(verbose_name=(('Gasfired', 'gasfired'), ('Turbojet', 'turbojet'), ('Windturbine', 'windturbine')))),
                ('efficiency', models.FloatField()),
                ('pmin', models.IntegerField()),
                ('pmax', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Historic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('call', models.CharField(max_length=10)),
                ('call_date', models.DateTimeField()),
                ('load', models.IntegerField()),
                ('gas_price', models.FloatField()),
                ('kerosine_price', models.FloatField()),
                ('windturbine_percentage', models.FloatField()),
                ('powerplants', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapi.powerplants')),
            ],
            options={
                'ordering': ['call'],
            },
        ),
    ]
